sfdx-spa-alcala/force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-spa-alcala/force-app/main/default/objects/Section__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Year</label>
    <referenceTo>Year__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Student_Subject_Grade__c/Student_Subject_Grade__c.object-meta.xml
<CustomObject>
    <label>Student Subject Grade</label>
    <nameField>
        <displayFormat>SG - {000000}</displayFormat>
        <label>Student Subject Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Subject Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-spa-alcala/force-app/main/default/objects/Student_Subject_Grade__c/fields/Final_Rating__c.field-meta.xml
<CustomField>
    <fullName>Final_Rating__c</fullName>
    <label>Final Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Student_Subject_Grade__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Subject Grades (Student)</relationshipLabel>
    <relationshipName>Student_Subject_Grades1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Student_Subject_Grade__c/fields/Student_Year_Semester__c.field-meta.xml
<CustomField>
    <fullName>Student_Year_Semester__c</fullName>
    <label>Student Year/Semester</label>
    <referenceTo>Student_Year_Semester__c</referenceTo>
    <relationshipLabel>Student Subject Grades</relationshipLabel>
    <relationshipName>Student_Subject_Grades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Student_Subject_Grade__c/fields/Teacher_Subject__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Subject__c</fullName>
    <label>Teacher Subject</label>
    <referenceTo>Teacher_Subject__c</referenceTo>
    <relationshipLabel>Student Subject Grades</relationshipLabel>
    <relationshipName>Student_Subject_Grades</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Student_Year_Semester__c/Student_Year_Semester__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>SY - {00000}</displayFormat>
        <label>Student Year/Semester Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-spa-alcala/force-app/main/default/objects/Student_Year_Semester__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Year__c</field>
            <operation>equals</operation>
            <valueField>Section__c.Year__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Section__c</referenceTo>
    <relationshipName>Student_Years_Semesters</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Student_Year_Semester__c/fields/Semester__c.field-meta.xml
<CustomField>
    <fullName>Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Semester</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Period_Semester__c.Section__c</field>
            <operation>equals</operation>
            <valueField>$Source.Section__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Period_Semester__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Student_Years_Semesters1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Student_Year_Semester__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Student</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Student_Year_Semester__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Type Grade and click the magnifying glass to display all the grade levels</inlineHelpText>
    <label>Year</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 9) AND (2 OR 3 OR 4 OR 5)) OR (6 AND (7 OR 8))</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Junior Highschool</value>
        </filterItems>
        <filterItems>
            <field>Year__c.Name</field>
            <operation>equals</operation>
            <value>Grade 7</value>
        </filterItems>
        <filterItems>
            <field>Year__c.Name</field>
            <operation>equals</operation>
            <value>Grade 8</value>
        </filterItems>
        <filterItems>
            <field>Year__c.Name</field>
            <operation>equals</operation>
            <value>Grade 9</value>
        </filterItems>
        <filterItems>
            <field>Year__c.Name</field>
            <operation>equals</operation>
            <value>Grade 10</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Senior Highschool</value>
        </filterItems>
        <filterItems>
            <field>Year__c.Name</field>
            <operation>equals</operation>
            <value>Grade 11</value>
        </filterItems>
        <filterItems>
            <field>Year__c.Name</field>
            <operation>equals</operation>
            <value>Grade 12</value>
        </filterItems>
        <filterItems>
            <field>$Source.School_Year_CY__c</field>
            <operation>equals</operation>
            <valueField>Year__c.School_Year__r.Id</valueField>
        </filterItems>
        <infoMessage>Type Grade and click Go to display all the grade levels</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Year__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Student_Years_Semesters</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Subjects__c/Subjects__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subjects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-spa-alcala/force-app/main/default/objects/Subjects__c/fields/Semester__c.field-meta.xml
<CustomField>
    <fullName>Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Semester</label>
    <referenceTo>Period_Semester__c</referenceTo>
    <relationshipLabel>Subjects</relationshipLabel>
    <relationshipName>Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Subjects__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subjects</relationshipLabel>
    <relationshipName>Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Subjects__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Year</label>
    <referenceTo>Year__c</referenceTo>
    <relationshipLabel>Subjects</relationshipLabel>
    <relationshipName>Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Teacher_Subject__c/Teacher_Subject__c.object-meta.xml
<CustomObject>
    <label>Teacher Subject</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Teacher Subject Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teacher Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-spa-alcala/force-app/main/default/objects/Teacher_Subject__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Teacher Subjects</relationshipLabel>
    <relationshipName>Teacher_Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Teacher_Subject__c/fields/Semester__c.field-meta.xml
<CustomField>
    <fullName>Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Semester</label>
    <referenceTo>Period_Semester__c</referenceTo>
    <relationshipLabel>Teacher Subjects</relationshipLabel>
    <relationshipName>Teacher_Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Teacher_Subject__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subjects__c</referenceTo>
    <relationshipLabel>Teacher Subjects</relationshipLabel>
    <relationshipName>Teacher_Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Teacher_Subject__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teacher Subjects</relationshipLabel>
    <relationshipName>Teacher_Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-spa-alcala/force-app/main/default/objects/Year__c/Year__c.object-meta.xml
<CustomObject>
    <label>Year</label>
    <nameField>
        <label>Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-spa-alcala/force-app/main/default/classes/EnrollmentTriggerHelper.cls
/**************************************************************************************************
* Name             : EnrollmentTriggerHelper                                                  
* Test Class       : EnrollmentTriggerHelper
* Version          : 1.0                                        
* Function         : Auto Create Subject and Grades                                
* ------------------------------------------------------------------------------------------------ 
* Change History    AUTHOR            DATE                Description                          
* CH00              Jose              24/03/2017                     

***************************************************************************************************/
public class EnrollmentTriggerHelper {


    public static void afterInsertHandler( List<Student_Year_Semester__c> newRecords ) { 
        
        List<Id> yearId = new List<Id>();
        Set<Id> sectionId = new Set<Id>();
        List<Id> semesterId = new List<Id>();
        Map<Id,Id> studentMap = new Map<Id,Id>();
        Map<Id,Student_Year_Semester__c> studentEnrollMap = new Map<Id,Student_Year_Semester__c>();
        String levelRecordType;
            
        List<Student_Subject_Grade__c> listSubjGrade = new List<Student_Subject_Grade__c>(); 
        for(Student_Year_Semester__c studYearSem: newRecords){
            yearId.add(studYearSem.Year__c);
            sectionId.add(studYearSem.Section__c);
            semesterId.add(studYearSem.Semester__c);
            studentMap.put(studYearSem.Id,StudYearSem.Student__c);
            studentEnrollMap.put(studYearSem.Id,studYearSem);
            levelRecordType = Schema.SObjectType.Student_Year_Semester__c.getRecordTypeInfosById().get(studYearSem.recordtypeid).getname();
        
            
        }
        system.debug('##record type is:'+levelRecordType);
        if(levelRecordType == 'Junior Highschool'){
            List<Teacher_Subject__c> listSubject = [SELECT Id,Subject__c,Section__c, Teacher__c FROM Teacher_Subject__c WHERE Subject__r.Active__c = true AND Section__c in: sectionId];
            
              for(Id enrollId: studentEnrollMap.keySet()){
                  
                  for(Teacher_Subject__c subj: listSubject){
                      if(studentEnrollMap.get(enrollId).Section__c == subj.Section__c){
                         Student_Subject_Grade__c studSubjGrade = new Student_Subject_Grade__c();
                         studSubjGrade.Student_Year_Semester__c = enrollId; 
                 //        studSubjGrade.Subject__c = subj.Subject__c;
                 //        studSubjGrade.Teacher__c = subj.Teacher__c;
                         studSubjGrade.Teacher_Subject__c = subj.id;
                         studSubjGrade.Final_Rating__c = 0;
                         studSubjGrade.Student__c = studentEnrollMap.get(enrollId).Student__c;
                         listSubjGrade.add(studSubjGrade);
                      }
              
              	}
              }
      
              if(!listSubjGrade.isEmpty()){
                    insert listSubjGrade;
              }
        }
        
       if(levelRecordType == 'Senior Highschool'){
            system.debug('##entered here at senior highschool');
           
          List<Teacher_Subject__c> listSubject = [SELECT Id,Subject__c,Teacher__c,Semester__c FROM Teacher_Subject__c WHERE Subject__r.Active__c = true AND Semester__c in: semesterId ];
         
           
             for(Id enrollId: studentEnrollMap.keySet()){
                  
                  for(Teacher_Subject__c subj: listSubject){
                      if(studentEnrollMap.get(enrollId).Semester__c == subj.Semester__c){
                         Student_Subject_Grade__c studSubjGrade = new Student_Subject_Grade__c();
                         studSubjGrade.Student_Year_Semester__c = enrollId; 
                //         studSubjGrade.Subject__c = subj.Subject__c;
                //         studSubjGrade.Teacher__c = subj.Teacher__c;
                           studSubjGrade.Final_Rating__c = 0;
                          studSubjGrade.Teacher_Subject__c = subj.id;
                //         studSubjGrade.Semester__c = subj.Semester__c;
                         studSubjGrade.Student__c = studentEnrollMap.get(enrollId).Student__c;
                         listSubjGrade.add(studSubjGrade);
                      }
              
              	}
              }
                
              if(!listSubjGrade.isEmpty()){
                    insert listSubjGrade;
              }
        }
        
        
    }
    
    public static void afterUpdateHandler( List<Student_Year_Semester__c> newRecords, MAP<Id, Student_Year_Semester__c> newRecordMap,MAP<Id, Student_Year_Semester__c> oldRecordMap ) { 
        
        List<Id> studYearSemIds = new List<Id>(); 
        List<Student_Year_Semester__c> studYearSemNew = new List<Student_Year_Semester__c>();
        
        for(Student_Year_Semester__c studYearSem: newRecords){
            studYearSemIds.add(studYearSem.Id);
        }
        
        List<Student_Subject_Grade__c> deleteStudentSubjGrade = [SELECT Id FROM Student_Subject_Grade__c WHERE Student_Year_Semester__c in: studYearSemIds];
                
        
        for(Student_Year_Semester__c studYearSem: newRecords){
           
      //      if( (oldRecordMap.get( studYearSem.Id ).Year__c != newRecordMap.get( studYearSem.Id ).Year__c) || (oldRecordMap.get( studYearSem.Id ).Section__c != newRecordMap.get( studYearSem.Id ).Section__c) || (oldRecordMap.get( studYearSem.Id ).Semester__c != newRecordMap.get( studYearSem.Id ).Semester__c) ){
                studYearSemNew = newRecords; 
                
      //      }
            
        }
        
        if(!studYearSemNew.isEmpty()){
            if(!deleteStudentSubjGrade.isEmpty()){
                Delete deleteStudentSubjGrade;
            }
            afterInsertHandler(studYearSemNew); 
            
        }
       
 
        
    }
   
    
}